asmolentzov/little-shop

db/migrate/20181215211532_create_users.rb
db/migrate/20181215211701_create_items.rb
db/migrate/20181215212307_create_orders.rb
db/migrate/20181215212910_create_order_items.rb
db/schema.rb

This pull request includes:
Migration files for all tables
Completed Schema

Dbase creation#78

---

db/migrate/20181215212910_create_order_items.rb
db/schema.rb

After talking with Ian, we changed the "status" field in order_items to "fulfilled"

Change OrderItem status to fulfilled

---

.gitignore
app/controllers/carts_controller.rb
app/controllers/items_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/controllers/welcome_controller.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/visitor_sees_nav_bar_spec.rb

Implements User Story 2
Adds Nav bar to application.html.erb with links across site.
Adds basic currently necessary routes. 
Does NOT implement shopping cart count - created new waffle card, 86, for that. 
All tests passing. Driver-navigator'd this with Dan
Closes #74

Visitor navigation#74

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/routes.rb
db/migrate/20181215211532_create_users.rb
db/schema.rb
spec/features/user_can_register_spec.rb
spec/features/user_show_page_spec.rb
spec/models/user_spec.rb

-Added feature tests for user registration
-Added model test for user email uniqueness
-Added default values for user role and user enabled columns
-Added helper method of current_user
-Added functionality for user story 7
closes #68

User registration#68

---

app/controllers/admin/users_controller.rb
app/controllers/application_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/admin_sees_nav_bar_spec.rb
spec/features/user_sees_nav_bar_spec.rb

Completes User Story 5
Adds specific links to admin user role nav bar. 
Adds enum specification to User model. 
All tests passing. 
Driver-navigator'd Anna & Will.
Closes #71

Admin navigation#71

---

app/models/user.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/merchant_sees_nav_bar_spec.rb
spec/features/user_can_register_spec.rb
spec/features/user_sees_nav_bar_spec.rb
spec/features/visitor_sees_nav_bar_spec.rb

-Added test for Merchant Navigation
-Added if else block to application.html.erb
driver navigator brad/dan
closes #72

Adds test for Merchant Navigation

---

app/views/layouts/application.html.erb

Merge conflict fixes for admin links. All tests passing.

Admin links merge conflict fix

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/users/new.html.erb
spec/features/user_can_register_spec.rb

Creates sad path test as per user story 9
Adds logic to user create method for flash messages per uniqueness of email
Adds to user new.html.erb to display messages and auto complete form 
Tests passing
will and dan driver / navigator
closes #66

Registration email#66

---

app/controllers/sessions_controller.rb
app/views/sessions/new.html.erb
app/views/welcome/index.html.erb
config/routes.rb
spec/features/visitor_can_login_spec.rb

User Story 10: User Can Login
Tests and implements login functionality, with users sent to appropriate paths by role after login. 
Creates session.
Displays flash message that the user has logged in successfully. 
All tests passing.
Driver-navigator'd Anna & Bradley
Closes #64

User login#64

---

app/controllers/sessions_controller.rb
app/views/sessions/new.html.erb
app/views/welcome/index.html.erb
config/routes.rb
spec/features/user_can_logout_spec.rb
spec/features/visitor_can_login_spec.rb

-Added feature tests for all user types logging out, being redirected to their respective pages, and seeing logout flash message
-All functionality for card 61 implemented with the exception of deletion of items in cart - moved to card 96
-All tests passing, 99% coverage
Driver navigator'd Brad and Anna
closes #61

User logout#61

---

app/controllers/sessions_controller.rb
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
app/views/users/show.html.erb
app/views/welcome/index.html.erb
config/routes.rb
spec/features/user_can_logout_spec.rb
spec/features/visitor_can_login_spec.rb

-Added feature test for user entering bad credentials when trying to log in
-Added functionality to redirect to the login page and display a flash message notifying the user that their credentials were incorrect.
-All tests passing, 99% coverage
Driver navigator'd Brad and Anna
Closes #63

Bad credentials#63

---

app/controllers/sessions_controller.rb
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
app/views/users/show.html.erb
app/views/welcome/index.html.erb
config/routes.rb
spec/features/user_can_logout_spec.rb
spec/features/visitor_can_login_spec.rb

-Added feature tests for logged in users being redirected to paths based on user role when they click on the login link.
-Added login in sessions controller to redirect based on role.
-Added flash messages to application.html.erb to show for all pages.
-All tests passing, 99% coverage.
Driver navigator'd Brad and Anna
Closes #62

Logged in redirected#62

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/index.html.erb
spec/features/merchant_index_page_spec.rb
spec/models/user_spec.rb

-Added feature test for merchant index page
-Added model test for User.merchants class method
-Implemented functionality to pass both new tests 
closes #23 
coded solo, requesting review.

Merchant index#23

---

app/controllers/users_controller.rb
app/views/users/new.html.erb
spec/features/user_can_register_spec.rb

Implements story #8, error checking for missing fields upon registration.
Also refines and refactors story #9 (unique email error checking) to be compatible with the changes.

Registration missing details#67

---

app/controllers/application_controller.rb
app/views/layouts/application.html.erb

Refactored the overall site nav bar to dry up code.
Separated the current configuration into three divs:
1) Welcome (Logged in as NAME)
2) Cart/Login/Registration/Profile
3) Other user functions 
All tests pass.

Refactoring of Nav Bars

---

.gitignore
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/items/index.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/features/admin_sees_nav_bar_spec.rb
spec/features/merchant_dashboard_spec.rb

Adds basic logic to items index controller
Adds filter to User show page
tests passing 
closes #28

Merchant dashboard#41

---

.gitignore
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/items/index.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/features/admin_sees_nav_bar_spec.rb
spec/features/merchant_dashboard_spec.rb
spec/features/user_show_page_spec.rb

Adds logic to users update controller to prevent users from editing their email address to one thats already in use. 
tests passing 
closes #52

Registered user uniq edit#52

---

app/controllers/items_controller.rb
app/views/items/index.html.erb
config/routes.rb
spec/features/item_index_page_spec.rb
spec/features/user_show_page_spec.rb

-Added feature test for all user types seeing all enabled items (user story 14)
-Implemented functionality to pass item index tests
- All tests passing
-100% coverage
closes #59

Items index#59

---

.gitignore
app/controllers/admin/users_controller.rb
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/items/index.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/features/admin_sees_merchant_info_spec.rb
spec/features/admin_sees_nav_bar_spec.rb
spec/features/merchant_dashboard_spec.rb
spec/features/user_show_page_spec.rb
spec/models/user_spec.rb

adds logic to users controller to filter error messages
adds logic to display enabled and disabled buttons
changes model validations to include true and false in enabled 
adds merchant? method  to return all merchants regardless of enabled being true or false 
adds model test for merchant?
adds antithesis test to enabled_merchant method
closes #21

Admin user#21

---

app/controllers/sessions_controller.rb
spec/features/user_can_logout_spec.rb

-Rewrote user logging out test to remove the allow_any_instance_of, as it was preventing our view from actually seeing the effect of the log out button since it was overriding the current_user method.
-Added the expectation to not see the log out link for test specificity.
-Added session.clear to the destroy method in the sessions controller.
-All tests passing.
-100% coverage.
closes #109

Logging out#109

---

app/controllers/admin/users_controller.rb
app/controllers/carts_controller.rb
app/controllers/users_controller.rb
app/models/cart.rb
app/models/user.rb
app/views/admin/users/index.html.erb
app/views/carts/show.html.erb
app/views/items/index.html.erb
app/views/users/index.html.erb
config/routes.rb
db/schema.rb
spec/features/admin_sees_merchant_info_spec.rb
spec/features/admin_user_index_page_spec.rb
spec/features/cart_show_page_spec.rb
spec/features/merchant_sees_nav_bar_spec.rb
spec/features/user_show_page_spec.rb
spec/models/cart_spec.rb
spec/models/user_spec.rb

Completes User Story #27
1. Creates cart
2 Adds Items to cart
3. Creates a cart show page with required info
Work done as a team.
Passes all tests.
Closes #44

User cart show page#44

---

app/controllers/admin/users_controller.rb
app/views/admin/users/show.html.erb
app/views/users/index.html.erb
config/routes.rb
spec/features/admin_sees_merchant_info_spec.rb

Adds amin merchants show route
adds show to admin controller
adds basic html to amin show.html.erb
tests passing 
closes #27

Admin visits merchant#27

---

app/controllers/admin/users_controller.rb
app/controllers/users_controller.rb
app/views/users/index.html.erb
config/routes.rb
spec/features/admin_sees_merchant_info_spec.rb

Adds enable routes 
Adds enable method
Adds current_admin? user_params 
tests passing 
take a solid look at this code its covers a few things we haven't learned yet
closes #19

Admin enables merchant#19

---

app/controllers/items_controller.rb
app/controllers/sessions_controller.rb
app/models/item.rb
app/models/order.rb
app/views/items/show.html.erb
spec/features/item_show_page_spec.rb
spec/features/user_can_logout_spec.rb
spec/models/item_spec.rb

-Adds feature test for item show page
-Adds model test for item avg_fulfill_time
-Implements functionality for card 57
-100% coverage
closes #57

Item show page#57

---

spec/features/admin_sees_merchant_info_spec.rb

-Unskipped line 4 test for admin sees merchant info test
-All tests passing except one skipped
Coded and reviewed as a team

Unnskips admin sees merchant test line 4

---

app/controllers/application_controller.rb
app/controllers/carts_controller.rb
app/controllers/items_controller.rb
app/models/cart.rb
app/views/layouts/application.html.erb
spec/features/user_sees_nav_bar_spec.rb
spec/features/visitor_sees_nav_bar_spec.rb
spec/models/cart_spec.rb

Completes user stories 2 & 3 by adding a functional number of items in cart to the nav bar for visitors and default users. 
- Updates feature tests for users and visitors seeing nav bar to include adding items to the cart and seeing the total update. 
- Creates the cart_count method to calculate the number of items in the cart, along with model test.
- Moves the setting of a cart to the application controller so that it is accessible anywhere, using the set_cart method. 
- Updates the nav bar cart view slightly: now the link to the cart is the word Cart along with the number of items, e.g.:  "Cart: 3"
- Tests all passing.
Closes #86

Nav bar cart#86

---

app/controllers/application_controller.rb
app/views/carts/show.html.erb
spec/features/admin_user_index_page_spec.rb
spec/features/registered_user_sees_an_empty_cart_spec.rb
spec/features/user_sees_an_empty_cart_spec.rb

Creates test for registered user viewing an empty cart
Creates test for non registered user viewing an empty cart
Adds if logic to cart show page 
close #43

User views empty cart#28

---

app/views/carts/show.html.erb
spec/features/visitor_checkout_spec.rb

-Adds test for visitor seeing a message to register or login to checkout. The words register and  log in are links. Added a sad path test to confirm that logged in user does not see this message. 
-Implements functionality to complete user story 31
closes #40

Visitor checkout#40

---

app/controllers/carts_controller.rb
app/controllers/items_controller.rb
app/views/items/show.html.erb
spec/features/item_show_page_spec.rb

Adds test for registered user adding item to cart
Adds test for visitor adding item to cart 
Edits path in item show 
tests passing 
closes #45

Visitor adds item to cart#26

---

app/controllers/carts_controller.rb
app/controllers/items_controller.rb
app/views/items/show.html.erb
spec/features/item_show_page_spec.rb
spec/features/user_can_logout_spec.rb

Branched off a branch here 
This is for Card 96 items are deleted from cart upon logout 
Wrote test 
Test passes nothing was added to the code base

Cart items deleted#96

---

app/assets/stylesheets/application.css
app/views/items/index.html.erb
app/views/items/show.html.erb
app/views/layouts/application.html.erb

-Changed item index photo tag to a different tag - photos show up now.
-Added some styling to the nav bar as well as the item index page and item show page. 
-Resized images for item index page as well as item show page.
closes #118

Pics showing up#118

---

spec/features/admin_user_profile_page_spec.rb

Writes test to check for redirect 
writes test to check for appropriate content 
tests passing
please review the wording of the card before merge
closes #47

Admin redirect#47

---

app/controllers/carts_controller.rb
app/views/admin/users/show.html.erb
app/views/carts/show.html.erb
config/routes.rb
spec/features/admin_user_profile_page_spec.rb
spec/features/cart_show_page_spec.rb

Adds test for removing an item, adding one, or removing one
Adds cart_item_path
Adds update item quantity method 
Adds merchant inventory check to method 
Creates flash to inform user merchant doesnt have enough stock (seemed like the best way to test)
test passing
Door is open to pass numerical quantity as opposed to just increments of one (its not part of the card but it may be a nice addition)
closes #41

User adjusts cart quantity#30

---

spec/features/admin_user_profile_page_spec.rb

writes test to check for redirect and appropriate links
No additional code needed
test passing 
closes #25

adds test for redirect tests passing

---

app/controllers/profile/orders_controller.rb
app/views/carts/show.html.erb
config/routes.rb
spec/features/cart_show_page_spec.rb

Completes User Story 32, Registered users can check out
- Adds Check Out button to Cart Show page
- Adds route for creating an order
- Adds create method to profile/orders controller
- All tests passing
***Please in particular look at the whole orders creation part. Does this seem like the right approach in terms of the route/controller used? What about the create method? There's a lot going on in there, but I'm not sure how to simplify it, or where it would be better to move the logic. 
Closes #39

Check out#39

---

spec/features/cart_show_page_spec.rb

- Fixes merge conflict missed 'end'
- Adds `inventory: 1` to test in cart_show_page_spec that was failing when run with full rspec

Fixes merge conflict and FactoryBot issue in test

---

app/controllers/items_controller.rb
app/models/item.rb
app/views/items/index.html.erb
app/views/items/new.html.erb
config/routes.rb
db/migrate/20181215211701_create_items.rb
db/schema.rb
spec/features/item_index_page_spec.rb
spec/features/merchant_new_item_spec.rb
spec/models/item_spec.rb

-Adds tests for merchant: 
1- seeing the add new item link
2- creating an item with valid information
3- creating an item without an image link
4- creating an item with a negative inventory (sad path)
-Implemented functionality for card 13
-All tests passing 
-99.95% coverage
closes #13

Merchant new item#13

---

app/controllers/items_controller.rb
app/views/items/index.html.erb
spec/features/merchant_item_index_spec.rb
spec/features/merchant_new_item_spec.rb

-Adds test for merchant disabling an item.
-Removed expectations from merchant new item test that snuck in on the last PR.
closes #16

Merchant disable item#16

---

app/controllers/admin/users_controller.rb
app/controllers/users_controller.rb
app/views/admin/users/show.html.erb
spec/features/admin_user_profile_page_spec.rb

Adds test fo display of user profile orders to admin within admin user profile view
Adds html and erb to display orders
Creates @orders var in admin user chow controller 
tests passing 
closes #49

Admin sees user order#49

---

app/controllers/profile/orders_controller.rb
app/models/order_item.rb
app/views/profile/orders/show.html.erb
config/routes.rb
spec/features/user_order_show_page_spec.rb
spec/models/item_spec.rb
spec/models/order_item_spec.rb

Adds conditional link to view for canceling order
Creates route to cancel an order (this route is an update as we want the order info to persist)
Creates update method
tests passing 
closes #35

User cancels an order#35

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/show.html.erb
config/routes.rb
spec/features/admin_user_order_show_page_spec.rb

Adds admin orders feature test page
Adds admin orders route
Adds admin orders controller
Adds admin orders show method
Adds admin orders show page 
Adds admin orders update method 
tests passing 
closes #34

Admin cancels a order#34

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/show.html.erb
config/routes.rb
spec/features/admin_user_order_show_page_spec.rb

Pulled code from PR #169 
Adds test to for Admin sees user order show page
test passing no additional code needed. 
closes #36

Admin views and order show page#36

---

app/models/user.rb
spec/factories/factory_bot.rb
spec/features/admin_user_index_page_spec.rb
spec/features/cart_show_page_spec.rb
spec/features/merchant_index_page_spec.rb
spec/features/user_can_logout_spec.rb
spec/features/user_can_register_spec.rb
spec/features/user_show_page_spec.rb
spec/features/visitor_can_login_spec.rb
spec/models/cart_spec.rb
spec/models/user_spec.rb

Changes all tests to include 5 digit zip code
Adds model test for 5 digit zip code length
Adds validation to model for 5 digit zip 
closes #119

Registration zip sad path#119

---

app/models/item.rb
spec/models/item_spec.rb

-Updates the avg_fulfill_time method in the item model to match Ian's solution
-Updates tests to pass
closes #117

Merchant Avg Fulfill Time Refactor

---

app/assets/stylesheets/application.css
app/views/carts/show.html.erb
app/views/welcome/index.html.erb
spec/features/cart_show_page_spec.rb

-Revised the way we put images into the view for the cart show page with image_tags.
-Revised the image paths in the cart show tests
-Added a basic welcome message to the welcome/root page.
closes #126

Cart thumbnails#126

---

app/assets/stylesheets/application.css
app/assets/stylesheets/application.scss
app/views/admin/users/index.html.erb
app/views/layouts/application.html.erb
app/views/users/index.html.erb
config/application.rb

- Updates assets with asset tags as needed for proper asset pipeline management. 
- Now see all styling/images in `rails s -e production`
- All tests passing

Asset pipeline

---

app/controllers/admin/merchants_controller.rb
app/controllers/carts_controller.rb
app/views/users/index.html.erb
config/routes.rb
spec/features/admin_sees_merchant_info_spec.rb

Adds link to downgrade a merchant to a user 
Adds route
Adds downgrade method
tests passing 
closes #26

Admin downgrades a merchant#26

---

app/controllers/admin/merchants_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/dashboard/order_items_controller.rb
app/views/admin/merchants/show.html.erb
app/views/admin/users/index.html.erb
config/routes.rb
spec/features/admin_manages_merchant_orders_spec.rb

Adds ability for admin to fulfill orders on behalf of a merchant. 
Updates to controller, routes, and views.
All tests passing, 100% coverage. 
Closes #206

Admin merchant fulfill

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/admin/users/index.html.erb
app/views/admin/users/show.html.erb
app/views/profile/orders/show.html.erb
app/views/profile/users/show.html.erb
app/views/users/index.html.erb
spec/features/admin_user_index_page_spec.rb
spec/features/admin_user_profile_page_spec.rb
spec/features/merchant_dashboard_spec.rb
spec/features/merchant_index_page_spec.rb
spec/features/user_order_show_page_spec.rb
spec/features/user_show_page_spec.rb
spec/models/user_spec.rb

Minor fixes: 
- Updates top merchant by time method to be two methods -top and bottom - to push logic to model
- Updates views and corresponding tests with nicer date format
Closes #196

Minor fixes

---

app/views/admin/merchants/show.html.erb

Fixes style bug in admin merchant show page.
All tests passing.

Fixes style bug for admin merchant show
